import {createSlice} from "@reduxjs/toolkit";
import {bookInfo} from "./mocKData.js"


const bookListSlice =createSlice({

    name:"list",
    initialState :{
        items:bookInfo,
    },

    reducers: {
        addItem: (state,action) =>{
            state.items.push(action.payload);
        },
        removeItem: (state,action)=>{
            state.items.pop()
        },
        clearList: (state,action)=>{
            state.items.length =0;
        },
    }


})
// cartSlice.actions contains all action creators automatically generated by Redux;
export const{addItem ,reomoveItem,clearCart} = bookListSlice.actions;
export default bookListSlice.reducer;   //cartSlice.reducer must be default